USE [bg]
GO
/****** Object:  Table [dbo].[USER]    Script Date: 05/12/2012 14:32:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.[FAMILY]', 'U') IS NOT NULL
  DROP TABLE dbo.[FAMILY]


CREATE TABLE [dbo].[FAMILY](
	[email] [nvarchar](150) NOT NULL,
 CONSTRAINT [FAMILY_PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

